# Site wide configuration
theme: jekyll-theme-hacker
exclude: 
  - README.md
  - node_modules
title: neo
description: Personal Website
github: 
    is_project_page: false

params:
  description: "Nothing to see here folks"



